### ISSUE TITLE
open8021s support for ATH10k QCA6174 chipsets?

### ISSUE THREAD

**Issue by ngiftsun** [phillymesh/802.11s-adapters#6]
I would like to know if open80211s is supported for ath10k based QCA6174 devices. I could see a [firmware patch for QCA98XX](https://github.com/o11s/open80211s/wiki/ath10k-(802.11ac)-for-Mesh-Support) devices but I'm not sure about QCA6174 . I don't know what's the problem with my driver. I use [Compex WLT674](https://wikidevi.com/wiki/Compex_WLT674) card on Ubuntu 16.04 with a kernel version 4.4.x. I have verified that the card supports both mesh point & IBSS mode using **iw** but I get an error `SIOCSIFFLAGS: Invalid argument` when I try to bring up the mesh interface.  I tried to load ath10k_core module with rawmode=1 but the kernel fails to load the module complaining about the fact the firmware doesn't support it. I even tried the latest [firmware](https://github.com/kvalo/ath10k-firmware/tree/master/QCA6174) but did not really succeed.

Thanks in advance.

**Comment by darkdrgn2k** [comment]
Are you using HT40? What is the exact iw comment you are using

**Comment by ngiftsun** [comment]
@darkdrgn2k I apologize for my late response. I actually gave up on this card and used Ralinlink RT5572 chipset based dongle to move forward with out mesh network. Right now, I'm trying to mesh an 11ac card for better bandwidth. This is the script that I use to create a mesh. 
**script used to automate the mesh**
sudo systemctl stop network-manager >/dev/null 2>/dev/null || :
sudo ifconfig $MESH_IF down
sudo iw $MESH_IF set type mp
sudo ifconfig $MESH_IF up
sudo ifconfig $MESH_IF $MESH_IP
sudo iw dev $MESH_IF mesh join $MESH_NAME 
sudo iw dev $MESH_IF set mesh_param mesh_rssi_threshold -65
sudo ip route add default via $MESH_GW
I could still get the same error SIOCSIFFLAGS: Invalid argument for QCA6174 card. I'm using Ubuntu 4.16 kernel.

**Comment by Hurricos** [comment]
The response will be no; QCA6174 uses the ath10k driver, on which 802.11s is broken (and will probably remain broken for a while due to firmware issues in the publicly-released firmware due to [Qualcomm being greedy](https://github.com/openwrt/mt76/issues/72#issuecomment-434151124)).

You can get close. Check out [ath10k-ct](https://github.com/greearb/ath10k-ct), which supports 11ac (e.g. 80MHz-wide) IBSS.
